[[collection]]
type = "card_simple"
title = "Apple Developer Academy @ UC Jakarta"
date = "Mar 2026 - Present"
link = "https://developeracademy.apps.binus.ac.id/"
icon = "images/ic_appledev.webp"
content = "Cohort 2026"
featured = true

[[collection]]
type = "card_simple"
title = "Bangkit Academy 2024 Batch 2"
date = "Sep 2024 - Des 2024"
link = "https://id.wikipedia.org/wiki/Bangkit_Academy"
icon = "images/ic_bangkit.png"
content = "Cloud Computing Cohort"
featured = false

[[collection]]
type = "card_simple"
title = "University of Amikom Yogyakarta"
date = "Sep 2022 - Present"
link = "https://home.amikom.ac.id/"
icon = "images/ic_amikom.png"
content = "Informatics Students"
featured = false
