[[collection]]
type = "entry"
title = "Dart"
icon = "/images/ic_dart.png"

[[collection]]
type = "entry"
title = "Kotlin"
icon = "/images/ic_kotlin.png"

[[collection]]
type = "entry"
title = "PHP"
icon = "/images/ic_php.png"

[[collection]]
type = "entry"
title = "Javascript"  
icon = "/images/ic_js.png"

[[collection]]
type = "entry"
title = "Flutter"
icon = "/images/ic_flutter.png"

[[collection]]
type = "entry"
title = "Jetpack Compose"
icon = "/images/ic_jetpackcompose.png"

[[collection]]
type = "entry"
title = "Nodejs"
icon = "/images/ic_nodejs.png"

[[collection]]
type = "entry"
title = "Docker"
icon = "/images/ic_docker.png"

[[collection]]
type = "entry"
title = "Google Cloud"
icon = "/images/ic_gcp.png"


[[collection]]
type = "entry"
title = "Linux"
icon = "/images/ic_linux.png"


[[collection]]
type = "entry"
title = "Laravel"
subtitle = "currently learning"
icon = "/images/ic_laravel.png"

[[collection]]
type = "entry"
title = "AWS"
subtitle = "currently learning"
icon = "/images/ic_aws.png"